### ISSUE TITLE
Docs UI

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.Developer.Doc#2]
Nice to see this repo 👌

A few days ago I did a quick test with https://vuepress.vuejs.org/ (you actually don't need to know Vue if you are using the default setup) and it's pretty easy to setup https://github.com/jmsaulnier/Elastos.ORG.Docs and deploy https://github.com/jmsaulnier/Elastos.ORG.Docs/blob/master/package.json#L23 (the best would be to add a CNAME file to the branch linked to https://docs.elastos.org/ for example)
The result looks great https://jmsaulnier.github.io/Elastos.ORG.Docs/

ARK project is a good example how they are using it https://github.com/ArkEcosystem/docs

**Comment by xuliting** [comment]
I am very honored to see your suggestion on the code repository of Elastos. Thank you for your support and contribution to Elastos, we will consider your proposal.

In order to better promote the work and facilitate communication, please provide your WeChat number. We will add you to our developer documentation group, and we will work together to create a bright future for Elastos. Alternatively, you can choose to add our staff (WeChat: xlt_lemon_xx, Please indicate your GitHub account number).

Your contribution to Elastos, when we review and merge it, we will give you the ELA award. Please provide your ELA wallet address.

You can also give a brief introduction to yourself about your current location, job, role and your interests. Maybe we can also cooperate in depth to achieve a win-win situation.

Thank you very much.

**Comment by xuliting** [comment]
Hi, jmsaulnier. We attach great importance to the issue made by the contributors. After the approval is passed, you will be rewarded. Please contact me in time, or you can send an email directly to Dev-support@elastos.org with your GitHub account number and ELA wallet address. After we confirm it, we will send the corresponding reward to your wallet. Thank you very much!

**Comment by jmsaulnier** [comment]
@xuliting are you agree with this proposal? If yes I can push a PR this week

**Comment by xuliting** [comment]
I agree with your suggestion and look forward to your contribution. Thank you very much.

**Comment by xuliting** [comment]
Currently, the developer website is under development, please wait.

**Comment by jmsaulnier** [comment]
@xuliting great news! Let me know if you need help
